### ISSUE TITLE
iOS & IL2CPP : Refactor custom attributes with parameters

### ISSUE THREAD

**Issue by flashman1234** [christerk/FFBUnity#3]
Reflected custom attributes with parameters cause an error on the iPad app with the following error:

The scripting backend (IL2CPP) doesn't support Reflection (actual error:  Unsupported internal call for IL2CPP:CustomAttributeData::ResolveArgumentsInternal - "IL2CPP does not support inspection of attribute constructor arguments at run time."

**Comment by christerk** [comment]
Should be fixed as of d60bd5b
